import { useEffect, useState, type FormEvent } from "react";
import { useApi } from "../../Context/ApiContext";
import type { ProfileSettings } from "../../types";
import { FormField } from "../FormField/FormField";
import "./SettingsPage.css";

type SettingsForm = ProfileSettings & { displayName: string };
const defaults: ProfileSettings = { discordHandle: "", discordUserId: "", addressLine1: "", addressLine2: "", postalCode: "", city: "", country: "", payoutMethod: "Bank transfer", payoutAccountHolder: "", payoutIban: "", payoutBic: "", payoutBankName: "", revolutRevtag: "", paymentCardBrand: "Visa", paymentCardNumber: "", paymentCardCvv: "", paymentCardExpiryMonth: "01", paymentCardExpiryYear: String(new Date().getFullYear()), paymentCardLast4: "", paymentCardExpiry: "", pushoverUserKey: "", sheetsGoogleAccount: "", sheetsDocumentUrl: "", sheetsConfirmationMode: "discord-confirmation", tikeyConnected: false, ticketmasterAccountsCsv: "", axsAccountsCsv: "" };

export function SettingsPage() {
  const { user, updateMe } = useApi();
  if (!user) return null;
  const buildForm = (): SettingsForm => ({ displayName: user.displayName, ...defaults, ...user.profileSettings });
  const [form, setForm] = useState<SettingsForm>(buildForm); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => setForm(buildForm()), [user]);
  const update = (name: string, value: string | boolean) => setForm((current) => ({ ...current, [name]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); try { const { displayName, ...profileSettings } = form; await updateMe({ displayName: displayName.trim(), profileSettings }); setMessage("Settings saved."); } catch (requestError) { setMessage(requestError instanceof Error ? requestError.message : "Unable to save settings."); } finally { setSaving(false); } };
  return <form className="settings-page page-stack" onSubmit={submit}>
    <section className="panel page-panel settings-section"><div className="page-header"><div><h2>Personal details</h2><p>Identity and contact information used throughout LisTix.</p></div></div><div className="settings-fields"><FormField label="Display name" name="displayName" value={form.displayName} onChange={update} /><FormField label="Discord handle" name="discordHandle" value={form.discordHandle} onChange={update} /><FormField label="Discord user ID" name="discordUserId" value={form.discordUserId} onChange={update} /><FormField label="Address" name="addressLine1" value={form.addressLine1} onChange={update} /><FormField label="Address line 2" name="addressLine2" value={form.addressLine2} onChange={update} /><FormField label="Postal code" name="postalCode" value={form.postalCode} onChange={update} /><FormField label="City" name="city" value={form.city} onChange={update} /><FormField label="Country" name="country" value={form.country} onChange={update} /></div></section>
    <section className="panel page-panel settings-section"><div className="page-header"><div><h2>Payout</h2><p>Destination for marketplace payouts.</p></div></div><div className="settings-fields"><FormField label="Payout method" name="payoutMethod" value={form.payoutMethod} options={["Bank transfer", "Revolut"]} onChange={update} />{form.payoutMethod === "Revolut" ? <FormField label="Revtag" name="revolutRevtag" value={form.revolutRevtag} onChange={update} /> : <><FormField label="Account holder" name="payoutAccountHolder" value={form.payoutAccountHolder} onChange={update} /><FormField label="IBAN" name="payoutIban" value={form.payoutIban} onChange={update} /><FormField label="BIC" name="payoutBic" value={form.payoutBic} onChange={update} /><FormField label="Bank name" name="payoutBankName" value={form.payoutBankName} onChange={update} /></>}</div></section>
    <section className="panel page-panel settings-section"><div className="page-header"><div><h2>Payment card</h2><p>Card used for inventory purchases.</p></div></div><div className="settings-fields"><FormField label="Card brand" name="paymentCardBrand" value={form.paymentCardBrand} options={["Visa", "MasterCard"]} onChange={update} /><FormField label="Card number" name="paymentCardNumber" value={form.paymentCardNumber} onChange={update} /><FormField label="CVV" name="paymentCardCvv" value={form.paymentCardCvv} type="password" onChange={update} /><FormField label="Expiry month" name="paymentCardExpiryMonth" value={form.paymentCardExpiryMonth} options={Array.from({ length: 12 }, (_, i) => String(i + 1).padStart(2, "0"))} onChange={update} /><FormField label="Expiry year" name="paymentCardExpiryYear" value={form.paymentCardExpiryYear} options={Array.from({ length: 12 }, (_, i) => String(new Date().getFullYear() + i))} onChange={update} /></div></section>
    <section className="panel page-panel settings-section"><div className="page-header"><div><h2>Connections</h2><p>External accounts and automated synchronization.</p></div></div><div className="settings-fields"><FormField label="Pushover user key" name="pushoverUserKey" value={form.pushoverUserKey} onChange={update} /><FormField label="Ticketmaster accounts CSV" name="ticketmasterAccountsCsv" value={form.ticketmasterAccountsCsv} type="url" onChange={update} /><FormField label="AXS accounts CSV" name="axsAccountsCsv" value={form.axsAccountsCsv} type="url" onChange={update} /><FormField label="Google account" name="sheetsGoogleAccount" value={form.sheetsGoogleAccount} type="email" onChange={update} /><FormField label="Google Sheets document" name="sheetsDocumentUrl" value={form.sheetsDocumentUrl} type="url" onChange={update} /><label className="toggle-field"><input type="checkbox" checked={form.tikeyConnected} onChange={(event) => update("tikeyConnected", event.target.checked)} /><span>Tikey connected</span></label></div></section>
    <div className="settings-actions">{message && <p className={message === "Settings saved." ? "success-message" : "error-message"}>{message}</p>}<button className="secondary-button" type="button" onClick={() => setForm(buildForm())}>Reset</button><button className="primary-button" disabled={saving}>{saving ? "Saving..." : "Save settings"}</button></div>
  </form>;
}
